application: pik2ascii
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img  
- url: /css
  static_dir: css
- url: /js
  static_dir: js  
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest 